# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmWM965sLVCSvepw1-cNXX-3INnzjba4

#실습1번
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

sns.scatterplot(data=df, x="온도", y="압력", alpha=0.5)

plt.title("온도와 압력의 관계 (음의 관계 경향)")
plt.xlabel("온도(℃)")
plt.ylabel("압력")

plt.show()

"""#실습2번"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

sns.scatterplot(data=df, x="온도", y="전류", hue="판정", alpha=0.7)

plt.title("판정별 온도-전류 산점도 (위험 영역 탐색)")
plt.xlabel("온도")
plt.ylabel("전류")

plt.show()

"""#실습3번"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

corr = df.corr(numeric_only=True)

plt.figure(figsize=(8, 6))
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0)

plt.title("센서 상관관계 Heatmap")
plt.show()

print("상관행렬 결과:\n", corr.round(2))

"""#실습4번"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(15, 5))

sns.countplot(data=df, x="설비라인", ax=ax1)
ax1.set_title("설비라인별 데이터 개수")

ax2.set_title("온도 분포")

sns.boxplot(data=df, x="설비라인", y="진동", ax=ax3)
ax3.set_title("라인별 진동 분포(박스플롯)")

plt.suptitle("종합 시각화 리포트 1", fontsize=14, fontweight="bold")
plt.tight_layout()

plt.show()