# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxQWo1SHK7OFHtB22KepTyRPkqBW1OCU

#실습1번
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(data=df, x="전류")

plt.title("전류 분포")
plt.xlabel("전류 (A)")
plt.ylabel("빈도수 (Count)")

plt.show()

"""#실습2번"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

bins_list = [10, 20, 40]

for i, b in enumerate(bins_list):
    sns.histplot(data=df, x="전류", bins=b, kde=True, ax=axes[i])

    axes[i].set_title(f"전류 분포 (bins={b})")
    axes[i].set_xlabel("전류 (A)")
    axes[i].set_ylabel("빈도수 (Count)")

plt.tight_layout()
plt.show()

"""#실습3번"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(data=df, x="온도", hue="판정", kde=True)

plt.title("양품·불량 온도 분포 비교")
plt.xlabel("온도 (℃)")
plt.ylabel("빈도수 (Count)")

plt.show()

"""#실습4번"""

import matplotlib.pyplot as plt
import seaborn as sns

sensor_info = {
    "온도": "℃",
    "진동": "mm/s",
    "전류": "A"
}

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i, (col, unit) in enumerate(sensor_info.items()):
    sns.histplot(data=df, x=col, kde=True, ax=axes[i])

    axes[i].set_title(f"{col} 분포")
    axes[i].set_xlabel(f"{col} ({unit})")
    axes[i].set_ylabel("빈도수 (Count)")

plt.tight_layout()
plt.show()

"""#실습5번"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(data=df, y="전류")

plt.title("전류 박스플롯")
plt.ylabel("전류 (A)")

plt.show()

"""#실습6번"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(data=df, x="설비라인", y="온도", hue="판정")

plt.title("라인별 및 판정별 온도 분포 비교")
plt.xlabel("설비라인")
plt.ylabel("온도 (℃)")

plt.show()