# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17n4k9pOGnb-nARVjbqExtSV3QymPXzzx

#실습1번
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/cmapss_fd001_sample.csv')

engine2 = df[df['unit_nr'] == 2]
x = engine2['time_cycles']

y = engine2['s_2']

plt.figure(figsize=(10, 5))
plt.plot(x, y, color='blue', linewidth=1.5)

plt.title('2번 엔진의 s_2 센서 시계열 변화', fontsize=14)
plt.xlabel('가동 회차 (Time Cycles)', fontsize=12)
plt.ylabel('센서 값 (s_2)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)

plt.show()

"""#실습2번"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/cmapss_fd001_sample.csv')
engine2 = df[df['unit_nr'] == 2]
x = engine2['time_cycles']
y_original = engine2['s_2']

y_moving_avg = y_original.rolling(window=10).mean()

plt.figure(figsize=(10, 5))

plt.plot(x, y_original, color='lightgray', label='원본 (s_2)', linewidth=1.5)

plt.plot(x, y_moving_avg, color='blue', label='이동평균 (window=10)', linewidth=2)

plt.title('센서 원본 데이터와 이동평균선 비교', fontsize=14)
plt.xlabel('가동 회차 (Time Cycles)', fontsize=12)
plt.ylabel('센서 값', fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)


plt.show()

"""#실습3번"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/cmapss_fd001_sample.csv')
engine2 = df[df['unit_nr'] == 2]
x = engine2['time_cycles']
y_original = engine2['s_2']

plt.figure(figsize=(12, 6))
plt.plot(x, y_original, color='lightgray', label='원본 (s_2)', linewidth=1.2)

windows = [5, 20, 50]
colors = ['green', 'orange', 'red']

for w, color in zip(windows, colors):
    y_ma = y_original.rolling(window=w).mean()
    plt.plot(x, y_ma, color=color, label=f'이동평균 (window={w})', linewidth=2)

plt.title('윈도우 크기별 이동평균선 비교 (5 vs 20 vs 50)', fontsize=14)
plt.xlabel('가동 회차 (Time Cycles)', fontsize=12)
plt.ylabel('센서 값', fontsize=12)
plt.legend(fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)

plt.show()

"""#실습4번"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/cmapss_fd001_sample.csv')
engine1 = df[df['unit_nr'] == 1]
x = engine1['time_cycles']

sensors = ['s_2', 's_7']
colors = ['red', 'blue']

plt.figure(figsize=(10, 5))

for sensor, color in zip(sensors, colors):

    y_ma = engine1[sensor].rolling(window=20).mean()

    y_ma_scaled = (y_ma - y_ma.min()) / (y_ma.max() - y_ma.min())

    plt.plot(x, y_ma_scaled, color=color, label=f'{sensor} 이동평균 (window=20)', linewidth=2)

plt.title('여러 센서의 추세 방향 비교 (0~1 스케일 조정)', fontsize=14)
plt.xlabel('가동 회차 (Time Cycles)', fontsize=12)
plt.ylabel('센서 값 (정규화 됨)', fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)

plt.show()

"""#실습5번"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/cmapss_fd001_sample.csv')
engine1 = df[df['unit_nr'] == 1]
x = engine1['time_cycles']
y_original = engine1['s_3']

y_std = y_original.rolling(window=20).std()

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

ax1.plot(x, y_original, color='gray', label='원본 (s_3)', linewidth=1.5)
ax1.set_title('원본 데이터 시계열', fontsize=14)
ax1.set_ylabel('센서 값', fontsize=12)
ax1.legend(loc='upper left')
ax1.grid(True, linestyle='--', alpha=0.6)

ax2.plot(x, y_std, color='red', label='이동표준편차 (window=20)', linewidth=2)
ax2.set_title('이동표준편차를 통한 변동성 분석', fontsize=14)
ax2.set_xlabel('가동 회차 (Time Cycles)', fontsize=12)
ax2.set_ylabel('표준편차 값', fontsize=12)

ax2.axvspan(150, x.max(), color='yellow', alpha=0.3, label='불안정(변동성 급증) 구간')
ax2.legend(loc='upper left')
ax2.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()