# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cTjDoXeQFNkzZ3F_kwr141yGwHP88cq

#실습1번
"""

import pandas as pd

df = pd.read_csv('cmapss_fd001_sample.csv')

print("데이터 크기(행, 열):", df.shape)
print("\n열(컬럼) 이름:\n", df.columns)

print("\n데이터 앞부분 미리보기:")
print(df.head())

"""#실습2번"""

num_engines = df['unit_nr'].nunique()
print(f"총 엔진 대수: {num_engines}대")

engine_cycle_counts = df['unit_nr'].value_counts().sort_index()
print("\n엔진별 작동 회차(cycle) 길이:")
print(engine_cycle_counts)

"""#실습3번"""

df_engine_2 = df[df['unit_nr'] == 2]

target_sensors = ['s_2', 's_11', 's_12']

sensor_stats = df_engine_2[target_sensors].describe()
print("2번 엔진의 주요 센서 요약 통계:")
print(sensor_stats)

"""#실습4번"""

sensor_cols = [f's_{i}' for i in range(1, 22)]

sensor_stds = df[sensor_cols].std()

dropped_sensors = sensor_stds[sensor_stds == 0].index.tolist()
print("제외 대상 센서 (값이 늘 같음):", dropped_sensors)

selected_sensors = sensor_stds[sensor_stds > 0].index.tolist()
print("\n분석 대상 센서 (변화가 뚜렷함):")
print(selected_sensors)

missing_counts = df.isnull().sum()
total_missing = missing_counts.sum()

print(f"\n전체 결측치 개수: {total_missing}개")
if total_missing == 0:
    print("결과: 데이터에 결측(빈 값)이 없습니다.")
else:
    print("결측치가 존재하는 열:\n", missing_counts[missing_counts > 0])

"""#실습5번"""

df_engine_2 = df[df['unit_nr'] == 2].sort_values(by='time_cycles')

sensor_up = 's_11'
sensor_down = 's_7'

first_up = df_engine_2[sensor_up].iloc[0]
last_up = df_engine_2[sensor_up].iloc[-1]

first_down = df_engine_2[sensor_down].iloc[0]
last_down = df_engine_2[sensor_down].iloc[-1]

print(f"■ {sensor_up} 센서 변화")
print(f"첫 값: {first_up:.2f} -> 끝 값: {last_up:.2f}")
if last_up > first_up:
    print("판정: 상승 추세입니다.\n")
else:
    print("판정: 상승 추세가 아닙니다.\n")

print(f"■ {sensor_down} 센서 변화")
print(f"첫 값: {first_down:.2f} -> 끝 값: {last_down:.2f}")
if last_down < first_down:
    print("판정: 하강 추세입니다.")
else:
    print("판정: 하강 추세가 아닙니다.")

"""#실습6번"""

import matplotlib.pyplot as plt

df_engine_2 = df[df['unit_nr'] == 2].sort_values(by='time_cycles')

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(df_engine_2['time_cycles'], df_engine_2['s_11'], color='red')
plt.title('Sensor s_11 (Upward Trend)')
plt.xlabel('Time Cycles')
plt.ylabel('Sensor Value')

plt.subplot(1, 2, 2)
plt.plot(df_engine_2['time_cycles'], df_engine_2['s_7'], color='blue')
plt.title('Sensor s_7 (Downward Trend)')
plt.xlabel('Time Cycles')
plt.ylabel('Sensor Value')

plt.tight_layout()
plt.show()