# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YXJUNJ2DZIttDQWG6dNFa6hNYE8ugCd

#실습6번
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose

daily_data = ts['s_2'].resample('D').mean()
daily_data = daily_data.dropna()

decomposition = seasonal_decompose(daily_data, model='additive', period=7)

fig = decomposition.plot()
fig.set_size_inches(10, 8)
plt.tight_layout()
plt.show()