# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0NwUAvLptDc4tZg-8Ek4MhxmzkLwkoe

#실습1번
"""

import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

days = ['월', '화', '수', '목', '금']
temperatures = [62, 63, 65, 68, 72]

plt.plot(days, temperatures)
plt.show()

"""#실습2번"""

import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

df = pd.read_csv('17_열처리.csv')
df_a = df[df['설비명'] == 'A호기']

plt.figure(figsize=(8, 4))
plt.plot(df_a['일자'], df_a['온도'])
plt.title('기본 선 그래프')
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(df_a['일자'], df_a['온도'], color='red')
plt.title('색상(color)이 적용된 그래프')
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(df_a['일자'], df_a['온도'], color='red', linestyle='--', marker='o')
plt.title('색상, 선 스타일, 마커가 모두 적용된 그래프')
plt.show()

"""#실습3번"""

import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

df = pd.read_csv('설비센서_샘플.csv')
df_a = df[df['설비명'] == 'A호기']
df_c = df[df['설비명'] == 'C호기']

plt.figure(figsize=(8, 4))

plt.plot(df_c['일자'], df_c['온도'], marker='o', color='blue', label='C호기')

plt.title('C호기 온도 추세')
plt.xlabel('일자')
plt.ylabel('온도')
plt.legend()
plt.show()

plt.figure(figsize=(10, 4))

plt.plot(df_a['일자'], df_a['온도'], marker='s', color='red', label='A호기')

plt.plot(df_c['일자'], df_c['온도'], marker='o', color='blue', label='C호기')

plt.legend()

plt.title('A호기 및 C호기 온도 비교')
plt.xlabel('일자')
plt.ylabel('온도')
plt.show()

"""#실습4번"""

import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

x = [1, 2, 3, 4, 5]
a_temp = [75, 76, 78, 80, 83]
b_temp = [70, 72, 71, 74, 75]

plt.figure(figsize=(10, 4))

plt.plot(x, a_temp, color='red', marker='o', label='A호기')
plt.plot(x, b_temp, color='blue', marker='s', linestyle='--', label='B호기')

plt.title('A호기와 B호기 일자별 온도 변화 비교')
plt.xlabel('일자')
plt.ylabel('온도(℃)')

plt.legend(loc='upper left')

plt.show()

"""#실습5번"""

import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

data = {
    '일자': [1, 2, 3, 4, 5]*3,
    '설비명': ['A호기']*5 + ['B호기']*5 + ['C호기']*5,
    '온도': [75, 76, 78, 80, 83, 70, 72, 71, 74, 75, 62, 63, 65, 68, 72]
}
df = pd.DataFrame(data)

plt.figure(figsize=(10, 5))

machines = ['A호기', 'B호기', 'C호기']
colors = ['red', 'blue', 'green']

for machine, color in zip(machines, colors):
    df_machine = df[df['설비명'] == machine]

    plt.plot(df_machine['일자'], df_machine['온도'], color=color, marker='o', label=machine)

plt.title('세 설비 일자별 온도 비교')
plt.xlabel('일자')
plt.ylabel('온도(℃)')
plt.legend(loc='upper left')
plt.grid(True, alpha=0.3)

plt.savefig('세_설비_온도_비교.png', dpi=150)

plt.show()

"""#실습6번"""

import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

data = {
    '일자': [1, 2, 3, 4, 5],
    '온도': [70, 72, 75, 78, 82],
    '소음': [65, 68, 70, 75, 80],
    '진동': [0.7, 0.75, 0.8, 0.9, 1.2]
}
df_c = pd.DataFrame(data)

plt.figure(figsize=(10, 5))

plt.plot(df_c['일자'], df_c['온도'], color='red', marker='o', label='온도')
plt.plot(df_c['일자'], df_c['소음'], color='blue', marker='s', label='소음')

plt.plot(df_c['일자'], df_c['진동'] * 100, color='green', marker='^', linestyle='--', label='진동(x100)')

plt.title('C호기 상태 종합(온도·진동·소음) 추세선 비교')
plt.xlabel('일자')
plt.ylabel('측정값')
plt.legend(loc='upper left')
plt.grid(True, alpha=0.3)

plt.show()