# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwywKXwllEULgcetjtlzGvNAkdLEObQA

#실습1번
"""

import pandas as pd

df = pd.read_csv('20_engine01_timestamp_sample.csv')
print(df['timestamp'].dtype)

df['timestamp'] = pd.to_datetime(df['timestamp'])

print(df['timestamp'].dtype)

"""#실습2번"""

import pandas as pd

print("연도 첫 값:", df['timestamp'].dt.year.iloc[0])
print("월 첫 값:", df['timestamp'].dt.month.iloc[0])
print("일 첫 값:", df['timestamp'].dt.day.iloc[0])
print("시간 첫 값:", df['timestamp'].dt.hour.iloc[0])

df['hour'] = df['timestamp'].dt.hour

print("\n새로 추가된 'hour' 열의 첫 세 값:")
print(df['hour'].head(3))

"""#실습3번"""

import pandas as pd

df = df.set_index('timestamp')

print("인덱스 종류:", type(df.index).__name__)

df = df.sort_index()

print("\n첫 시각:", df.index[0])
print("마지막 시각:", df.index[-1])
print("전체 행 수:", len(df), "행")

"""#실습4번"""

import pandas as pd

day_data = df.loc['2024-03-02']

period_data = df.loc['2024-03-05':'2024-03-07']

print("3월 2일 하루 행 수:", len(day_data), "행")
print("3월 5일~7일 사흘 행 수:", len(period_data), "행")

"""#실습5번"""

import pandas as pd

df_6h_mean = df.resample('6h').mean()
print("--- 6시간 단위 평균 (첫 행) ---")
print(df_6h_mean.head(1))

df_6h_max = df.resample('6h').max()
print("\n--- 6시간 단위 최댓값 (첫 행) ---")
print(df_6h_max.head(1))

first_mean = df_6h_mean.iloc[0, 0]
first_max = df_6h_max.iloc[0, 0]

print(f"\n첫 구간 평균: {first_mean:.2f}")
print(f"첫 구간 최댓값: {first_max:.2f}")
print(f"최댓값이 평균보다 높은가?: {first_max > first_mean}")

"""#실습6번"""

import pandas as pd

df_1h = df.resample('1h').mean()
df_6h = df.resample('6h').mean()
df_12h = df.resample('12h').mean()

print(f"1시간 단위 행 수: {len(df_1h)}행")
print(f"6시간 단위 행 수: {len(df_6h)}행")
print(f"12시간 단위 행 수: {len(df_12h)}행")

print(f"\n행 수 비교: {len(df_1h)} > {len(df_6h)} > {len(df_12h)}")