# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWbq6_S0WZGXsjMpWRNdxB1zw7VzZ7yv

#실습5번
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)
cycles = 200
data = {
    'cycle': np.arange(1, cycles + 1),
    's_2': np.random.normal(1590, 5, cycles),
    's_3': np.random.normal(1400, 4, cycles),
    's_4': np.random.normal(1000, 3, cycles),
    's_7': np.random.normal(550, 2, cycles)
}
engine1 = pd.DataFrame(data)

engine1.loc[180:, 's_2'] += np.linspace(0, 15, 20) + np.random.normal(0, 12, 20)
engine1.loc[180:, 's_3'] += np.linspace(0, 12, 20) + np.random.normal(0, 10, 20)
engine1.loc[180:, 's_7'] -= np.linspace(0, 10, 20)

sensors = ['s_2', 's_3', 's_4', 's_7']
window_size = 20

target_sensor = 's_2'
engine1['rolling_mean'] = engine1[target_sensor].rolling(window=window_size).mean()
engine1['rolling_std'] = engine1[target_sensor].rolling(window=window_size).std()

fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

axes[0].plot(engine1['cycle'], engine1[target_sensor], label='Original Signal', alpha=0.5, color='gray')
axes[0].plot(engine1['cycle'], engine1['rolling_mean'], label=f'Moving Average (win={window_size})', color='blue', linewidth=2)
axes[0].axvline(x=180, color='red', linestyle='--', label='Change Point (Cycle 180)')
axes[0].axvspan(180, 200, color='red', alpha=0.15, label='Suspicious Region')
axes[0].set_ylabel('Sensor Value')
axes[0].set_title(f'Engine 1 - {target_sensor} Trend & Change Point Detection')
axes[0].legend(loc='upper left')
axes[0].grid(True, linestyle=':', alpha=0.6)

axes[1].plot(engine1['cycle'], engine1['rolling_std'], label=f'Moving Std (win={window_size})', color='orange', linewidth=2)
axes[1].axvline(x=180, color='red', linestyle='--')
axes[1].axvspan(180, 200, color='red', alpha=0.15)
axes[1].set_xlabel('Cycle')
axes[1].set_ylabel('Volatility (Std Dev)')
axes[1].set_title(f'Engine 1 - {target_sensor} Volatility Tracking')
axes[1].legend(loc='upper left')
axes[1].grid(True, linestyle=':', alpha=0.6)

plt.tight_layout()
plt.show()

corr = engine1[sensors].corr()

plt.figure(figsize=(7, 5))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', vmin=-1, vmax=1, linewidths=0.5)
plt.title('Multi-Sensor Correlation Heatmap')
plt.show()

normal_std_avg = engine1.loc[:179, 'rolling_std'].mean()
abnormal_std_avg = engine1.loc[180:, 'rolling_std'].mean()
std_ratio = abnormal_std_avg / normal_std_avg