# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dBFNSAuFPKNwY6WicBU82WaMYaKc5IZ

#실습1번
"""

import matplotlib.pyplot as plt
import pandas as pd

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

data = {
    '설비': ['A호기', 'A호기', 'B호기', 'B호기', 'C호기', 'C호기'],
    '온도': [62, 66, 68, 72, 75, 79]
}
df = pd.DataFrame(data)

avg_temp = df.groupby('설비')['온도'].mean()

plt.figure(figsize=(6, 4))
colors = ['blue', 'blue', 'red']
plt.bar(avg_temp.index, avg_temp.values, color=colors, width=0.5)
plt.title('설비별 평균 온도 (세로 막대)')
plt.xlabel('설비')
plt.ylabel('평균 온도(℃)')
plt.show()

plt.figure(figsize=(6, 4))
plt.barh(avg_temp.index, avg_temp.values, color=colors, height=0.5)
plt.title('설비별 평균 온도 비교')
plt.xlabel('평균 온도(℃)')
plt.ylabel('설비')
plt.tight_layout()
plt.show()

"""#실습2번"""

import matplotlib.pyplot as plt
import pandas as pd

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

data = {
    '상태': ['정상']*17 + ['점검']*4,
    '구역': ['A구역']*10 + ['B구역']*7 + ['A구역']*2 + ['B구역']*2,
    '진동': [2.1, 2.2, 2.0, 2.1, 2.3, 2.1, 2.2, 2.0, 2.1, 2.1,
           3.1, 3.2, 3.0, 3.1, 3.3, 3.1, 3.2,
           5.5, 5.8,
           6.1, 6.2]
}
df = pd.DataFrame(data)

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
status_counts = df['상태'].value_counts()
plt.bar(status_counts.index, status_counts.values, color=['blue', 'red'], width=0.5)

plt.title('설비 상태별 개수')
plt.xlabel('상태')
plt.ylabel('개수')

for i, v in enumerate(status_counts.values):
    plt.text(i, v + 0.5, str(v), ha='center')

zone_vib_mean = df.groupby('구역')['진동'].mean()
plt.bar(zone_vib_mean.index, zone_vib_mean.values, color='green', width=0.5)

plt.title('구역별 평균 진동 비교')
plt.xlabel('구역')
plt.ylabel('평균 진동 (mm/s)')

plt.tight_layout()
plt.show()

"""#실습3번"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

np.random.seed(42)
data = {'온도': np.random.normal(loc=70, scale=5, size=100)}
df = pd.DataFrame(data)

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.hist(df['온도'], bins=5, color='skyblue', edgecolor='black')
plt.title('온도 구간별 개수 분포 (bins=5)')
plt.xlabel('온도(℃)')
plt.ylabel('설비 수(개)')

plt.subplot(1, 2, 2)
plt.hist(df['온도'], bins=20, color='salmon', edgecolor='black')
plt.title('온도 구간별 개수 분포 (bins=20)')
plt.xlabel('온도(℃)')
plt.ylabel('설비 수(개)')

plt.tight_layout()
plt.show()

"""#실습4번"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

np.random.seed(10)
temp_data = np.random.normal(loc=70, scale=5.6, size=100)
temp_data = (temp_data - temp_data.mean()) / temp_data.std(ddof=1) * 5.6 + 70.0
temp_data = np.sort(temp_data)
temp_data[-1], temp_data[-2], temp_data[-3] = 79.2, 78.1, 77.5
df = pd.DataFrame({'온도': temp_data})

mean_temp = df['온도'].mean()
std_temp = df['온도'].std()

abnormal_df = df[df['온도'] >= 78]
abnormal_count = len(abnormal_df)

print(f"▶ 온도 평균: {mean_temp:.1f} · 표준편차: {std_temp:.1f}")
print(f"▶ 78도 이상 이상 설비 수: {abnormal_count}대")

plt.figure(figsize=(8, 4.5))

plt.hist(df['온도'], bins=15, color='cornflowerblue', edgecolor='black')

plt.axvline(mean_temp, color='green', linestyle='--', linewidth=2, label=f'평균 ({mean_temp:.1f}℃)')
plt.axvline(78, color='red', linestyle=':', linewidth=2, label='이상 기준 (78℃ 이상)')

plt.title('센서값 온도 분포 히스토그램')
plt.xlabel('온도(℃)')
plt.ylabel('설비 수(대)')
plt.legend()

plt.tight_layout()
plt.show()

"""#실습5번"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

np.random.seed(42)
temp_data = np.random.uniform(50, 90, 60)
vib_data = temp_data * 0.06 - 1.5 + np.random.normal(0, 0.4, 60)

df = pd.DataFrame({'온도': temp_data, '진동': vib_data})

df['상태'] = ['점검' if v >= 3.0 else '정상' for v in df['진동']]

plt.figure(figsize=(8, 5))

normal_df = df[df['상태'] == '정상']
check_df = df[df['상태'] == '점검']

plt.scatter(normal_df['온도'], normal_df['진동'], color='blue', alpha=0.7, label='정상')
plt.scatter(check_df['온도'], check_df['진동'], color='red', alpha=0.7, label='점검')

plt.axhline(y=3.0, color='red', linestyle='--', linewidth=1.5, label='임계 기준선 (3.0)')

plt.title('센서 온도와 진동의 관계 분석 (산점도)')
plt.xlabel('온도(℃)')
plt.ylabel('진동(mm/s)')

plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""#실습6번"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

np.random.seed(42)
temp_data = np.random.uniform(50, 90, 50)
noise_data = temp_data * 0.8 + np.random.normal(0, 3, 50)

df = pd.DataFrame({'온도': temp_data, '소음': noise_data})

plt.figure(figsize=(7, 5))

plt.scatter(df['온도'], df['소음'], color='darkorange', alpha=0.8, edgecolors='black')

plt.title('온도와 소음 센서 간 관계 분석')
plt.xlabel('온도(℃)')
plt.ylabel('소음(dB)')

plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

corr_value = df['온도'].corr(df['소음'])
print(f"▶ 두 변수의 상관계수: {corr_value:.2f}")
print("▶ 관계 해석: 점들이 우상향 형태를 띠므로, 온도가 올라갈수록 소음도 함께 커지는 '양의 상관관계'를 보입니다.")